//项目启动初始化数据
//创建租户数据
  INSERT INTO "public"."tenant" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "address_line1", "address_line2", "city", "country", "deleted", "description", "email_address", "first_name", "last_name", "logo", "phone_number", "state", "status", "tenant_code", "tenant_name", "type", "website", "zip_code") VALUES ('1', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '0', 0, '0', '0', '0', '0', '', '0', '0', 0, '0', '0', 0, '0', '0');
//创建部门
  INSERT INTO "public"."depart" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "name", "short_name", "sort", "status", "tenant_id") VALUES ('1', NULL, NULL, NULL, NULL, '0', '0', 0, '0', '0', '0', 0, 0, '1');
//创建用户,账户,identity数据  devsuperadmin   Black.123!@#
  INSERT INTO "public"."user" ("id", "created_at", "created_by", "updated_at", "updated_by", "activate_token", "avatar", "deleted", "email", "first_name", "gender", "icon", "last_login_time", "last_name", "mobile", "password", "username") VALUES ('a683c203-5422-44c4-a892-26178173437c', '2022-12-24 02:50:16.627916', NULL, NULL, NULL, NULL, 'http://dummyimage.com/100x100', 0, 'devsuperadmin', NULL, 93, NULL, NULL, NULL, '13677152331', 'QdftBPCZIZklXITEPzoBeMITjjpwc+n7RaJkE0sH/aIkAroPFBBdRSa5liX7HIbQZWOKH+baxBOeK8JvFBLR0RaWHI23k5bULR6Iy/rDeieEgelmURom5iLTgIFlKYDQOCFfcUsbLckpTsROB+tl3wqRH7oET9oXLhSFPevZp97tueOV/t5xF/34HaSjS/90qpH75uFa3O0ifX72UGBriisSn9fCN9rr2FMA7fHxZ9T2I+5c7UGoIpM9bicvSvJKjiTTFIutqHz/15hobjNvMam99+SMZPgclPcJvUNkKHLpSOcCPQLAe4kScXUNdU8z0tllHbOf6bvC8/c0jAT/NQ==', 'devsuperadmin');
INSERT INTO "public"."account" ("id", "created_at", "created_by", "updated_at", "updated_by", "deleted", "identity",
                                "name", "tenant_id", "type", "user_id")
VALUES ('1104fe4f-dcb1-4b6f-94c6-6bbdfc900f8f', '2022-12-24 02:50:16.802927', NULL, NULL, NULL, 0, NULL, NULL, '1', '0',
        'a683c203-5422-44c4-a892-26178173437c');
INSERT INTO "public"."tb001_user" ("tb001_id", "tb001_email", "tb001_password", "user_id", "tb001_user_name")
VALUES ('312fb93d-c596-4947-801d-dc84bafd258f', 'devsuperadmin',
        'QdftBPCZIZklXITEPzoBeMITjjpwc+n7RaJkE0sH/aIkAroPFBBdRSa5liX7HIbQZWOKH+baxBOeK8JvFBLR0RaWHI23k5bULR6Iy/rDeieEgelmURom5iLTgIFlKYDQOCFfcUsbLckpTsROB+tl3wqRH7oET9oXLhSFPevZp97tueOV/t5xF/34HaSjS/90qpH75uFa3O0ifX72UGBriisSn9fCN9rr2FMA7fHxZ9T2I+5c7UGoIpM9bicvSvJKjiTTFIutqHz/15hobjNvMam99+SMZPgclPcJvUNkKHLpSOcCPQLAe4kScXUNdU8z0tllHbOf6bvC8/c0jAT/NQ==',
        'a683c203-5422-44c4-a892-26178173437c', 'devsuperadmin');



INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('987f8793-8ea9-4b97-867b-01e43ab921aa', NULL, NULL, NULL, NULL, 'b4907b4e-c2fd-40ab-8a19-d9b3f5aac62f', '1', 0, NULL, NULL, NULL, 'LEFT-MENU', 'authorization.list', '/identity-management/authorization-list', NULL, 1, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('15a15851-64ac-4405-bcf3-a68513d6e2a9', NULL, NULL, NULL, NULL, 'b4907b4e-c2fd-40ab-8a19-d9b3f5aac62f', '100', 0, NULL, NULL, NULL, 'LEFT-MENU', 'application', '/identity-management/application', NULL, 2, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('2ca50de8-e095-41ca-8a9c-042e4c6278e4', NULL, NULL, NULL, NULL, 'b4907b4e-c2fd-40ab-8a19-d9b3f5aac62f', '101', 0, NULL, NULL, NULL, 'LEFT-MENU', 'compliance', '/identity-management/compliance', NULL, 3, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('ac31a2bf-4269-4f49-81c9-155e36b7b2c3', NULL, NULL, NULL, NULL, 'b4907b4e-c2fd-40ab-8a19-d9b3f5aac62f', '103', 0, NULL, NULL, NULL, 'LEFT-MENU', 'scope.list', '/identity-management/scope-list', NULL, 4, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('a2e37885-8632-49fa-acc6-7083bf652754', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '201', 0, NULL, NULL, NULL, 'LEFT-MENU', 'menu.menu-list', '/system-management/menu-list', NULL, 1, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('bec90fd2-9e40-4957-9f09-eb2c4add3f96', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '202', 0, NULL, NULL, NULL, 'LEFT-MENU', 'dict.dict-list', '/system-management/dict', NULL, 2, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('372bca81-0f61-4d75-bb7a-d7ecec077ad5', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '203', 0, NULL, NULL, NULL, 'LEFT-MENU', 'tenant.tenant-list', '/system-management/tenant', NULL, 3, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('a0b7bbff-93ba-4587-bdad-13d7d2bdd170', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '204', 0, NULL, NULL, NULL, 'LEFT-MENU', 'organize.organize-list', '/system-management/organize', NULL, 4, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('4f654453-7dcc-470b-aa86-2a52d39d3c81', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '205', 0, NULL, NULL, NULL, 'LEFT-MENU', 'role.role-list', '/system-management/role', NULL, 5, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('b65637db-8db1-44ec-822e-0612f0e84324', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '206', 0, NULL, NULL, NULL, 'LEFT-MENU', 'user.user-list', '/system-management/user-list', NULL, 6, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('5ad13691-5289-4dd9-9696-5e624eb88262', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '207', 0, NULL, NULL, NULL, 'LEFT-MENU', 'account.account-list', '/system-management/account', NULL, 7, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('5e43c0e0-dc2d-4316-86ae-31aabb392f7a', NULL, NULL, NULL, NULL, 'b0b70f3e-1870-4d68-bcd2-a1f912ffc914', '208', 0, NULL, NULL, NULL, 'LEFT-MENU', 'permission.permission-list', '/system-management/permission', NULL, 8, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('b0b70f3e-1870-4d68-bcd2-a1f912ffc914', NULL, NULL, NULL, NULL, '0', 'systemManagement', 0, NULL, NULL, NULL, 'LEFT-MENU', 'system-management', '/system-management', NULL, 1, 1, 0, 0, NULL, NULL);
INSERT INTO "public"."sys_menu" ("id", "created_at", "created_by", "updated_at", "updated_by", "parent_id", "code", "deleted", "description", "hidden", "icon", "location", "name", "path", "permission", "sort", "status", "tenant_enable", "type", "url", "menu_name") VALUES ('b4907b4e-c2fd-40ab-8a19-d9b3f5aac62f', NULL, NULL, NULL, NULL, '0', 'identityManagement', 0, NULL, NULL, NULL, 'LEFT-MENU', 'identity-management', '/identity-management', NULL, 1, 1, 0, 0, NULL, NULL);




