spring:
  data:
    redis:
      database: ${gstdev.cloud.environment.redis.database}
      host: ${gstdev.cloud.environment.redis.host}
      password: ${gstdev.cloud.environment.redis.password}
      port: ${gstdev.cloud.environment.redis.port}
      timeout: 10000
      lettuce:
        pool:
          max-active: 10
          max-wait: 10000
          max-idle: 10
          min-idle: 5
  redisson:
    enabled: false
    single-server-config:
      address: redis://${spring.data.redis.host}:${spring.data.redis.port}
      password: ${spring.data.redis.password}