server:
    port: 8102
spring:
    application:
        name: gstdev-system
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${gstdev.cloud.endpoint.issuer-uri}
                    jwk-set-uri: ${gstdev.cloud.endpoint.jwk-set-uri}
                opaquetoken:
                    client-id: password-client
                    client-secret: 123456