server:
    port: 8104
spring:
    application:
        name: gstdev-storage
    servlet:
        multipart:
            max-request-size: 10MB
            max-file-size: 10MB
gstdev:
    cloud:
        storage:
            bucketName: verity-development
            aws:
                endpoint: https://verity-development.s3.amazonaws.com
                accessKey: q
                secretKey: 